from .base import BaseRenderer
from scripts.renderers.headers.device import DeviceRenderer
from scripts.renderers.headers.peripheral import PeripheralRenderer
from scripts.renderers.headers.register import RegisterRenderer
from scripts.renderers.cmake.device_cmake import DeviceCmakeRenderer
from scripts.renderers.linker.linker import LinkerRenderer
from scripts.renderers.headers.options import OptionsRenderer
from scripts.renderers.headers.tags import TagsRenderer
from scripts.renderers.headers.events import EventsRenderer