#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

CONFIGURATOR_RE = re.compile(
    r"""\busing\s+(?P<name>[A-Za-z_]\w*)\s*=\s*hal\s*::\s*Configurator\s*<""",
    re.VERBOSE,
)


def remove_comments_and_literals(source: str) -> str:
    token_re = re.compile(
        r'''(?P<string>"(?:\\.|[^"\\])*")|(?P<char>'(?:\\.|[^'\\])*')|(?P<line>//[^\n]*)|(?P<block>/\*.*?\*/)''',
        re.VERBOSE | re.DOTALL,
    )

    def replace(match: re.Match[str]) -> str:
        return "".join("\n" if c == "\n" else " " for c in match.group(0))

    return token_re.sub(replace, source)


def find_configurators(source: str) -> list[tuple[str, int]]:
    cleaned = remove_comments_and_literals(source)
    return [
        (m.group("name"), cleaned.count("\n", 0, m.start()) + 1)
        for m in CONFIGURATOR_RE.finditer(cleaned)
    ]


def make_include_path(header: Path, output: Path) -> str:
    try:
        return Path(os.path.relpath(header.resolve(), output.parent.resolve())).as_posix()
    except ValueError:
        return header.resolve().as_posix()


def generate_vector_cpp(output: Path, header: Path, configurator: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    include = make_include_path(header, output)
    output.write_text(
        f'''// Generated by find_configurator.py.\n// DO NOT EDIT.\n\n#include "{include}"\n\nextern "C"\n[[gnu::section(".isr_vector"), gnu::used]]\nconst auto g_VectorTable = {configurator}::VectorTable::build();\n\nextern "C" void _init() {{}}''',
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Find exactly one hal::Configurator alias and generate the ISR vector-table translation unit.")
    parser.add_argument("--header", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--print-configurator", action="store_true")
    args = parser.parse_args()

    header = Path(args.header)
    output = Path(args.output)

    if not header.is_file():
        print(f"error: configuration header not found: {header}", file=sys.stderr)
        return 1

    try:
        source = header.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        print(f"error: cannot read {header}: {exc}", file=sys.stderr)
        return 1

    matches = find_configurators(source)

    if not matches:
        print(f"error: no hal::Configurator alias found in {header}", file=sys.stderr)
        return 1

    if len(matches) > 1:
        print(f"error: multiple hal::Configurator aliases found in {header}:", file=sys.stderr)
        for name, line in matches:
            print(f"  {name} at {header}:{line}", file=sys.stderr)
        return 1

    configurator, _ = matches[0]

    try:
        generate_vector_cpp(output, header, configurator)
    except OSError as exc:
        print(f"error: cannot generate {output}: {exc}", file=sys.stderr)
        return 1

    if args.print_configurator:
        print(configurator)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
